cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    mohittest:
      email: mohit.laad@airindia.com
      failed_login_attempts: 0
      logged_in: false
      name: Mohit Laad
      password: mohit123
    opstechuser:
      email: ops.tech@airindia.com
      failed_login_attempts: 0
      logged_in: false
      name: Ops Tech User
      password: opstech123
pre-authorized:
  emails:
  - melsby@gmail.com